// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: RoomMsgProto.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Proto
{

    [global::ProtoBuf.ProtoContract(Name = @"join_player_info")]
    public partial class JoinPlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateRoomC2s : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int gameMode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateRoomS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ret_code", IsRequired = true)]
        public int RetCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int gameMode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinRoomC2s : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player", IsRequired = true)]
        public JoinPlayerInfo Player { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinRoomS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ret_code", IsRequired = true)]
        public int RetCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int gameMode { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int roomMasterPlayerUid { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int selfPlayerUid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaveRoomS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int playerUid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomMembersChangeS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"players")]
        public global::System.Collections.Generic.List<PlayerInfo> Players { get; } = new global::System.Collections.Generic.List<PlayerInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartGameC2s : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int gameCfgId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int gameMode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartGameS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ret_code", IsRequired = true)]
        public int RetCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int gameCfgId { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int gameMode { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"players")]
        public global::System.Collections.Generic.List<PlayerInfo> Players { get; } = new global::System.Collections.Generic.List<PlayerInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterMapS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ret_code", IsRequired = true)]
        public int RetCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int mapId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerMoveC2s : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int playerUid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public NetVector2 moveDir { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerMoveS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ret_code", IsRequired = true)]
        public int RetCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int playerUid { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public NetVector2 movePos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerDieS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int diePlayerUid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int rebornTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int killerPlayerUid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerRebornS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ret_code", IsRequired = true)]
        public int RetCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int playerUid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"pos", IsRequired = true)]
        public NetVector2 Pos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerPathChangeS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int playerUid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"operate", IsRequired = true)]
        public int Operate { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"pos", IsRequired = true)]
        public NetVector2 Pos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CampAreaChangeS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"camp", IsRequired = true)]
        public int Camp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"pos", IsRequired = true)]
        public NetVector2 Pos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameEndS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"players")]
        public global::System.Collections.Generic.List<PlayerInfo> Players { get; } = new global::System.Collections.Generic.List<PlayerInfo>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
