// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: RoomMsgProto.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinRoomC2s : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player")]
        public PlayerInfo Player { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinRoomS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ret_code")]
        public int RetCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"players")]
        public global::System.Collections.Generic.List<PlayerInfo> Players { get; } = new global::System.Collections.Generic.List<PlayerInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaveRoomS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int playerUid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartGameC2s : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartGameS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ret_code")]
        public int RetCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterMapS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ret_code")]
        public int RetCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int mapId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerMoveC2s : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int playerUid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public NetVector2 moveDir { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerMoveS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ret_code")]
        public int RetCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int playerUid { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public NetVector2 movePos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerDieS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int diePlayerUid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int rebornTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int killerPlayerUid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerRebornS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int playerUid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"pos")]
        public NetVector2 Pos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerPathChangeS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int playerUid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"operate")]
        public int Operate { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"pos")]
        public NetVector2 Pos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CampAreaChangeS2c : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"camp")]
        public int Camp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"pos")]
        public NetVector2 Pos { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
