// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: TypesProto.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Proto
{

    [global::ProtoBuf.ProtoContract(Name = @"net_vector2_int")]
    public partial class NetVector2Int : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public int Y { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"net_vector2")]
    public partial class NetVector2 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x", IsRequired = true)]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y", IsRequired = true)]
        public float Y { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"gamer_info")]
    public partial class GamerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
        public string Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id", IsRequired = true)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"camp", IsRequired = true)]
        public int Camp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"pos", IsRequired = true)]
        public NetVector2 Pos { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"rotation", IsRequired = true)]
        public float Rotation { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public float moveSpeed { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
